from sense_hat import SenseHat
import time

sense = SenseHat()


#Task 4
sense = SenseHat()
red = (255, 0, 0)
orange = (255, 127, 0)
yellow =(255, 255, 0)
green = (0, 255, 0)
blue = (0,0,255)
indigo = (75, 0, 130)
white = (255, 255, 255)
black = (0,0,0)

while True:
    sense.set_pixel(0, 0, red)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(0, 1, orange)
    sense.set_pixel(1, 0, orange)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(0, 2, yellow)
    sense.set_pixel(2, 0, yellow)
    sense.set_pixel(1, 1, yellow)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(0, 3, green)
    sense.set_pixel(2, 1, green)
    sense.set_pixel(1, 2, green)
    sense.set_pixel(3, 0, green)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(0, 4, blue)
    sense.set_pixel(3, 1, blue)
    sense.set_pixel(2, 2, blue)
    sense.set_pixel(1, 3, blue)
    sense.set_pixel(4, 0, blue)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(0, 5, indigo)
    sense.set_pixel(4, 1, indigo)
    sense.set_pixel(3, 2, indigo)
    sense.set_pixel(2, 3, indigo)
    sense.set_pixel(1, 4, indigo)
    sense.set_pixel(5, 0, indigo)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(0, 6, white)
    sense.set_pixel(1, 5, white)
    sense.set_pixel(2, 4, white)
    sense.set_pixel(3, 3, white)
    sense.set_pixel(4, 2, white)
    sense.set_pixel(5, 1, white)
    sense.set_pixel(6, 0, white)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(0, 7, black)
    sense.set_pixel(1, 6, black)
    sense.set_pixel(2, 5, black)
    sense.set_pixel(3, 4, black)
    sense.set_pixel(4, 3, black)
    sense.set_pixel(5, 2, black)
    sense.set_pixel(6, 1, black)
    sense.set_pixel(7, 0, black)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(1, 7, white)
    sense.set_pixel(2, 6, white)
    sense.set_pixel(3, 5, white)
    sense.set_pixel(4, 4, white)
    sense.set_pixel(5, 3, white)
    sense.set_pixel(6, 2, white)
    sense.set_pixel(7, 1, white)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(2, 7, indigo)
    sense.set_pixel(3, 6, indigo)
    sense.set_pixel(4, 5, indigo)
    sense.set_pixel(5, 4, indigo)
    sense.set_pixel(6, 3, indigo)
    sense.set_pixel(7, 2, indigo)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(3, 7, blue)
    sense.set_pixel(4, 6, blue)
    sense.set_pixel(5, 5, blue)
    sense.set_pixel(6, 4, blue)
    sense.set_pixel(7, 3, blue)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(4, 7, green)
    sense.set_pixel(5, 6, green)
    sense.set_pixel(6, 5, green)
    sense.set_pixel(7, 4, green)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(5, 7, yellow)
    sense.set_pixel(6, 6, yellow)
    sense.set_pixel(7, 5, yellow)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(6, 7, orange)
    sense.set_pixel(7, 6, orange)
    time.sleep(1)
    sense.clear()
    sense.set_pixel(7, 7, red)
    time.sleep(1)
    sense.clear()
